import type {
  Shelf,
  InventoryItem,
  AlertLog,
  ActivityEvent,
  AIRecommendation,
  WorkerState,
  TaskItem,
  ManualTaskState,
} from "./types";

export const initialShelves: Record<string, Shelf> = {
  A1: {
    id: "A1",
    name: "Shelf A1",
    zone: "Zone A",
    status: "verified",
    assignedSKUs: ["SKU-E01", "SKU-E02", "SKU-E03"],
    position: [-4, 1, -2],
  },
  A2: {
    id: "A2",
    name: "Shelf A2",
    zone: "Zone A",
    status: "verified",
    assignedSKUs: ["SKU-E04", "SKU-E05", "SKU-E06"],
    position: [-4, 1, 0],
  },
  A3: {
    id: "A3",
    name: "Shelf A3",
    zone: "Zone A",
    status: "verified",
    assignedSKUs: ["SKU-E07", "SKU-E08", "SKU-E09"],
    position: [-4, 1, 2],
  },
  B1: {
    id: "B1",
    name: "Shelf B1",
    zone: "Zone B",
    status: "verified",
    assignedSKUs: ["SKU-F01", "SKU-F02", "SKU-F03"],
    position: [0, 1, -2],
  },
  B2: {
    id: "B2",
    name: "Shelf B2",
    zone: "Zone B",
    status: "verified",
    assignedSKUs: [],
    position: [0, 1, 0],
  },
  B3: {
    id: "B3",
    name: "Shelf B3",
    zone: "Zone B",
    status: "verified",
    assignedSKUs: [],
    position: [0, 1, 2],
  },
  C1: {
    id: "C1",
    name: "Shelf C1",
    zone: "Zone C",
    status: "verified",
    assignedSKUs: ["SKU-B01", "SKU-B02", "SKU-B03"],
    position: [4, 1, -2],
  },
  C2: {
    id: "C2",
    name: "Shelf C2",
    zone: "Zone C",
    status: "verified",
    assignedSKUs: ["SKU-B04", "SKU-B05", "SKU-B06"],
    position: [4, 1, 0],
  },
  C3: {
    id: "C3",
    name: "Shelf C3",
    zone: "Zone C",
    status: "verified",
    assignedSKUs: [],
    position: [4, 1, 2],
  },
  H1: {
    id: "H1",
    name: "Shelf H1",
    zone: "Hazard Storage",
    status: "verified",
    assignedSKUs: ["SKU-H01", "SKU-H03"],
    position: [-8, 1, -4],
  },
  H2: {
    id: "H2",
    name: "Shelf H2",
    zone: "Hazard Storage",
    status: "error",
    assignedSKUs: ["SKU-H02"],
    position: [-8, 1, 4],
  },
  F1: {
    id: "F1",
    name: "Shelf F1",
    zone: "Cold Storage",
    status: "verified",
    assignedSKUs: [],
    position: [8, 1, -4],
  },
  F2: {
    id: "F2",
    name: "Shelf F2",
    zone: "Cold Storage",
    status: "pending",
    assignedSKUs: [],
    position: [8, 1, 4],
  },
  REC: {
    id: "REC",
    name: "Receiving Area",
    zone: "Receiving Area",
    status: "pending",
    assignedSKUs: [],
    position: [0, -0.3, 9],
  },
};

export const initialInventory: InventoryItem[] = [
  // Beverages (Zone C)
  {
    sku: "SKU-B01",
    name: "Sprite Bottles",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C1",
    currentShelf: "C1",
    status: "verified",
    quantity: 186,
  },
  {
    sku: "SKU-B02",
    name: "Coca-Cola",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C1",
    currentShelf: "C1",
    status: "verified",
    quantity: 240,
  },
  {
    sku: "SKU-B03",
    name: "Pepsi",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C1",
    currentShelf: "C1",
    status: "verified",
    quantity: 150,
  },
  {
    sku: "SKU-B04",
    name: "Fanta",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C2",
    currentShelf: "C2",
    status: "verified",
    quantity: 110,
  },
  {
    sku: "SKU-B05",
    name: "Red Bull",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C2",
    currentShelf: "C2",
    status: "verified",
    quantity: 380,
  },
  {
    sku: "SKU-B06",
    name: "Minute Maid",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C2",
    currentShelf: "C2",
    status: "verified",
    quantity: 95,
  },
  {
    sku: "SKU-B07",
    name: "SmartWater",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C3",
    currentShelf: "C3",
    status: "verified",
    quantity: 300,
  },
  {
    sku: "SKU-B08",
    name: "Ginger Ale",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C3",
    currentShelf: "C3",
    status: "verified",
    quantity: 120,
  },

  // Food (Zone B)
  {
    sku: "SKU-F01",
    name: "Rice Bags",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 80,
  },
  {
    sku: "SKU-F02",
    name: "Sugar Sacks",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 65,
  },
  {
    sku: "SKU-F03",
    name: "Flour Tubs",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 45,
  },
  {
    sku: "SKU-F04",
    name: "Salt Cartons",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 200,
  },
  {
    sku: "SKU-F05",
    name: "Cooking Oil",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 120,
  },
  {
    sku: "SKU-F06",
    name: "Oatmeal Boxes",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 160,
  },
  {
    sku: "SKU-F07",
    name: "Pasta Packs",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 400,
  },
  {
    sku: "SKU-F08",
    name: "Honey Jars",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 85,
  },

  // Electronics (Zone A)
  {
    sku: "SKU-E01",
    name: "USB Cables",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 1200,
  },
  {
    sku: "SKU-E02",
    name: "Monitors",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 35,
  },
  {
    sku: "SKU-E03",
    name: "Keyboards",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 90,
  },
  {
    sku: "SKU-E04",
    name: "Routers",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 42,
  },
  {
    sku: "SKU-E05",
    name: "SSDs",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 180,
  },
  {
    sku: "SKU-E06",
    name: "Headsets",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 60,
  },
  {
    sku: "SKU-E07",
    name: "Mousepads",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 250,
  },
  {
    sku: "SKU-E08",
    name: "USB Hubs",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 140,
  },
  {
    sku: "SKU-E09",
    name: "Webcams",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 70,
  },

  // Furniture (Zone A)
  {
    sku: "SKU-U01",
    name: "Office Chairs",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 24,
  },
  {
    sku: "SKU-U02",
    name: "Tables",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 12,
  },
  {
    sku: "SKU-U03",
    name: "Cabinets",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 8,
  },
  {
    sku: "SKU-U04",
    name: "Office Desks",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 15,
  },
  {
    sku: "SKU-U05",
    name: "Bookshelves",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 10,
  },
  {
    sku: "SKU-U06",
    name: "Bar Stools",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 40,
  },

  // Industrial (Zone A)
  {
    sku: "SKU-I01",
    name: "M3 Bolts",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 5000,
  },
  {
    sku: "SKU-I02",
    name: "Bearings",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 350,
  },
  {
    sku: "SKU-I03",
    name: "Motors",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 18,
  },
  {
    sku: "SKU-I04",
    name: "Washers",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 4000,
  },
  {
    sku: "SKU-I05",
    name: "Gears",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 150,
  },
  {
    sku: "SKU-I06",
    name: "Hex Nuts",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 6000,
  },
  {
    sku: "SKU-I07",
    name: "Drive Belts",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 80,
  },

  // Medical (Zone B)
  {
    sku: "SKU-M01",
    name: "Gloves Box",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 500,
  },
  {
    sku: "SKU-M02",
    name: "Syringes",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 1200,
  },
  {
    sku: "SKU-M03",
    name: "Face Masks",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 2000,
  },
  {
    sku: "SKU-M04",
    name: "Bandages",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 800,
  },

  // Refrigerated Medical
  {
    sku: "SKU-M05",
    name: "Vaccine Coolbox",
    category: "Refrigerated Medical",
    zone: "Cold Storage",
    assignedShelf: "F1",
    currentShelf: "F1",
    status: "verified",
    quantity: 12,
  },

  // Cleaning Supplies (Zone B)
  {
    sku: "SKU-C01",
    name: "Sanitizer Bottles",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 140,
  },
  {
    sku: "SKU-C02",
    name: "Detergent Jugs",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 85,
  },
  {
    sku: "SKU-C03",
    name: "Mop Refills",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 150,
  },
  {
    sku: "SKU-C04",
    name: "Bleach Containers",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 60,
  },
  {
    sku: "SKU-C05",
    name: "Sponge Packs",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 300,
  },

  // Hazardous (Hazard Storage H1 / H2)
  {
    sku: "SKU-H01",
    name: "Industrial Paint",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 45,
  },
  {
    sku: "SKU-H02",
    name: "Batteries",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H2",
    currentShelf: "H1",
    status: "error",
    quantity: 220,
  }, // Misplaced
  {
    sku: "SKU-H03",
    name: "Chemical Solvents",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 30,
  },
  {
    sku: "SKU-H04",
    name: "Thinners",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 50,
  },
  {
    sku: "SKU-H05",
    name: "Aerosol Sprays",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 400,
  },
  {
    sku: "SKU-H06",
    name: "Motor Oil",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 110,
  },
];

export const initialAlerts: AlertLog[] = [
  {
    id: "alert-1",
    timestamp: "14:20:10",
    severity: "critical",
    message:
      "Batteries misplaced on shelf H1 instead of assigned H2. Expected: Hazard Storage. Status: Misplaced",
    resolved: false,
    shelfId: "H1",
  },
];

export const initialActivities: ActivityEvent[] = [
  {
    id: "act-1",
    time: "14:15:32",
    message: "Shelf verified: A1.",
    type: "success",
  },
  {
    id: "act-2",
    time: "14:18:12",
    message: "Telemetry reader online.",
    type: "success",
  },
  {
    id: "act-3",
    time: "14:20:10",
    message: "Item misplaced: Batteries on H1.",
    type: "error",
  },
  {
    id: "act-4",
    time: "14:25:02",
    message: "Shelf needs verification: F2.",
    type: "warning",
  },
];

export const initialRecommendations: AIRecommendation[] = [
  {
    id: "rec-1",
    title: "Relocate Fast-Moving Items",
    description:
      "M3 Bolts have high pick volume. Shift closer to Dispatch Area to reduce picker walking times.",
    impact: "18% efficiency increase",
    type: "layout",
    active: true,
  },
  {
    id: "rec-2",
    title: "Isolate High Temperature Battery Cell",
    description:
      "Batteries are currently near paint solvents. Relocate H2 contents to climate-controlled Cold Box.",
    impact: "Safety risk averted",
    type: "safety",
    active: true,
  },
];

export const initialWorkers: Record<string, WorkerState> = {
  alpha: {
    id: "alpha",
    name: "Alpha Forklift",
    status: "idle",
    position: [-6, -0.3, 9],
    basePosition: [-6, -0.3, 9],
    targetShelfId: null,
    currentTaskId: null,
    progress: 0,
    label: "Worker Idle",
    path: null,
    pathIndex: 0,
    carriedItemName: null,
    color: "#FF6B35",
  },
  beta: {
    id: "beta",
    name: "Beta Forklift",
    status: "idle",
    position: [6, -0.3, 9],
    basePosition: [6, -0.3, 9],
    targetShelfId: null,
    currentTaskId: null,
    progress: 0,
    label: "Worker Idle",
    path: null,
    pathIndex: 0,
    carriedItemName: null,
    color: "#5A5D64",
  },
};

export const initialTaskQueue: TaskItem[] = [
  {
    id: "task-1",
    itemName: "Batteries",
    itemShelfId: "H1",
    correctShelfId: "H2",
    status: "pending",
    assignedWorkerId: null,
    type: "automated",
  },
];

export const initialManualTask: ManualTaskState = {
  workerId: null,
  step: "none",
  itemName: null,
  itemShelfId: null,
  correctShelfId: null,
};
