import type { InsertProduct } from "./schema.ts";

export const seedProducts: InsertProduct[] = [
  // Beverages (Zone C)
  {
    sku: "SKU-B01",
    name: "Sprite Bottles",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C1",
    currentShelf: "C1",
    status: "verified",
    quantity: 186,
  },
  {
    sku: "SKU-B02",
    name: "Coca-Cola",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C1",
    currentShelf: "C1",
    status: "verified",
    quantity: 240,
  },
  {
    sku: "SKU-B03",
    name: "Pepsi",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C1",
    currentShelf: "C1",
    status: "verified",
    quantity: 150,
  },
  {
    sku: "SKU-B04",
    name: "Fanta",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C2",
    currentShelf: "C2",
    status: "verified",
    quantity: 110,
  },
  {
    sku: "SKU-B05",
    name: "Red Bull",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C2",
    currentShelf: "C2",
    status: "verified",
    quantity: 380,
  },
  {
    sku: "SKU-B06",
    name: "Minute Maid",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C2",
    currentShelf: "C2",
    status: "verified",
    quantity: 95,
  },
  {
    sku: "SKU-B07",
    name: "SmartWater",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C3",
    currentShelf: "C3",
    status: "verified",
    quantity: 300,
  },
  {
    sku: "SKU-B08",
    name: "Ginger Ale",
    category: "Beverages",
    zone: "Zone C",
    assignedShelf: "C3",
    currentShelf: "C3",
    status: "verified",
    quantity: 120,
  },

  // Food (Zone B)
  {
    sku: "SKU-F01",
    name: "Rice Bags",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 80,
  },
  {
    sku: "SKU-F02",
    name: "Sugar Sacks",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 65,
  },
  {
    sku: "SKU-F03",
    name: "Flour Tubs",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 45,
  },
  {
    sku: "SKU-F04",
    name: "Salt Cartons",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 200,
  },
  {
    sku: "SKU-F05",
    name: "Cooking Oil",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 120,
  },
  {
    sku: "SKU-F06",
    name: "Oatmeal Boxes",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 160,
  },
  {
    sku: "SKU-F07",
    name: "Pasta Packs",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 400,
  },
  {
    sku: "SKU-F08",
    name: "Honey Jars",
    category: "Food",
    zone: "Zone B",
    assignedShelf: "B1",
    currentShelf: "B1",
    status: "verified",
    quantity: 85,
  },

  // Electronics (Zone A)
  {
    sku: "SKU-E01",
    name: "USB Cables",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 1200,
  },
  {
    sku: "SKU-E02",
    name: "Monitors",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 35,
  },
  {
    sku: "SKU-E03",
    name: "Keyboards",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 90,
  },
  {
    sku: "SKU-E04",
    name: "Routers",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 42,
  },
  {
    sku: "SKU-E05",
    name: "SSDs",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 180,
  },
  {
    sku: "SKU-E06",
    name: "Headsets",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 60,
  },
  {
    sku: "SKU-E07",
    name: "Mousepads",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 250,
  },
  {
    sku: "SKU-E08",
    name: "USB Hubs",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 140,
  },
  {
    sku: "SKU-E09",
    name: "Webcams",
    category: "Electronics",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 70,
  },

  // Furniture (Zone A)
  {
    sku: "SKU-U01",
    name: "Office Chairs",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 24,
  },
  {
    sku: "SKU-U02",
    name: "Tables",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 12,
  },
  {
    sku: "SKU-U03",
    name: "Cabinets",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 8,
  },
  {
    sku: "SKU-U04",
    name: "Office Desks",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 15,
  },
  {
    sku: "SKU-U05",
    name: "Bookshelves",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 10,
  },
  {
    sku: "SKU-U06",
    name: "Bar Stools",
    category: "Furniture",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 40,
  },

  // Industrial (Zone A)
  {
    sku: "SKU-I01",
    name: "M3 Bolts",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 5000,
  },
  {
    sku: "SKU-I02",
    name: "Bearings",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 350,
  },
  {
    sku: "SKU-I03",
    name: "Motors",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A1",
    currentShelf: "A1",
    status: "verified",
    quantity: 18,
  },
  {
    sku: "SKU-I04",
    name: "Washers",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 4000,
  },
  {
    sku: "SKU-I05",
    name: "Gears",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A2",
    currentShelf: "A2",
    status: "verified",
    quantity: 150,
  },
  {
    sku: "SKU-I06",
    name: "Hex Nuts",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 6000,
  },
  {
    sku: "SKU-I07",
    name: "Drive Belts",
    category: "Industrial",
    zone: "Zone A",
    assignedShelf: "A3",
    currentShelf: "A3",
    status: "verified",
    quantity: 80,
  },

  // Medical (Zone B)
  {
    sku: "SKU-M01",
    name: "Gloves Box",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 500,
  },
  {
    sku: "SKU-M02",
    name: "Syringes",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 1200,
  },
  {
    sku: "SKU-M03",
    name: "Face Masks",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 2000,
  },
  {
    sku: "SKU-M04",
    name: "Bandages",
    category: "Medical",
    zone: "Zone B",
    assignedShelf: "B2",
    currentShelf: "B2",
    status: "verified",
    quantity: 800,
  },

  // Refrigerated Medical
  {
    sku: "SKU-M05",
    name: "Vaccine Coolbox",
    category: "Refrigerated Medical",
    zone: "Cold Storage",
    assignedShelf: "F1",
    currentShelf: "F1",
    status: "verified",
    quantity: 12,
  },

  // Cleaning Supplies (Zone B)
  {
    sku: "SKU-C01",
    name: "Sanitizer Bottles",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 140,
  },
  {
    sku: "SKU-C02",
    name: "Detergent Jugs",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 85,
  },
  {
    sku: "SKU-C03",
    name: "Mop Refills",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 150,
  },
  {
    sku: "SKU-C04",
    name: "Bleach Containers",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 60,
  },
  {
    sku: "SKU-C05",
    name: "Sponge Packs",
    category: "Cleaning Supplies",
    zone: "Zone B",
    assignedShelf: "B3",
    currentShelf: "B3",
    status: "verified",
    quantity: 300,
  },

  // Hazardous (Hazard Storage H1 / H2)
  {
    sku: "SKU-H01",
    name: "Industrial Paint",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 45,
  },
  {
    sku: "SKU-H02",
    name: "Batteries",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H2",
    currentShelf: "H1",
    status: "error",
    quantity: 220,
  },
  {
    sku: "SKU-H03",
    name: "Chemical Solvents",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 30,
  },
  {
    sku: "SKU-H04",
    name: "Thinners",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 50,
  },
  {
    sku: "SKU-H05",
    name: "Aerosol Sprays",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 400,
  },
  {
    sku: "SKU-H06",
    name: "Motor Oil",
    category: "Hazardous",
    zone: "Hazard Storage",
    assignedShelf: "H1",
    currentShelf: "H1",
    status: "verified",
    quantity: 110,
  },
];
