  import React, { useState, useRef, useEffect } from "react";
import { Send, BrainCircuit, Terminal, Sparkles, User } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { db } from "../db/index";
import { products } from "../db/schema";
import { productToInventoryItem } from "../db/utils";

interface Message {
  id: string;
  sender: "user" | "assistant";
  text: string;
  timestamp: string;
}

export const AIAssistantView: React.FC = () => {
  // 1. Live Context from TanStack Query
  const { data: cachedInventory } = useQuery({
    queryKey: ["products"],
    queryFn: async () => {
      const allProducts = await db.select().from(products);
      return allProducts.map(productToInventoryItem);
    },
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
  });

  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isThinking, setIsThinking] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isThinking]);

  const addMessage = (sender: "user" | "assistant", text: string) => {
    const time = new Date().toTimeString().split(" ")[0];
    setMessages((prev) => [
      ...prev,
      { id: `msg-${Date.now()}`, sender, text, timestamp: time },
    ]);
  };

  const executeCommand = async (query: string) => {
    setIsThinking(true);

    try {
      // 2. Data Privacy Guard - only feed what's needed
      const safeInventory = (cachedInventory || []).map((item) => ({
        sku: item.sku,
        name: item.name,
        category: item.category,
        currentShelf: item.currentShelf,
        status: item.status,
        quantity: item.quantity,
        zone: item.zone,
      }));

      const historyMessages = messages.map((m) => ({
        role: m.sender,
        content: m.text,
      }));

      // 3. Native call to local LLama 3.1 
      const apiResponse = await fetch("http://localhost:11434/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "llama3.1",
          messages: [
            {
              role: "system",
              content: `You are Invenio OS Assistant, a professional Warehouse Intelligence Copilot.

RULES FOR RESPONSES:
1. Speak in a concise, supervisor-ready operational tone.
2. ALWAYS format responses using specific headers and bullet lists.
3. Base ALL your answers on the live database context provided below.

Live Database Context Snapshot:
${JSON.stringify(safeInventory, null, 2)}`,
            },
            ...historyMessages,
            { role: "user", content: query },
          ],
        }),
      });

      if (!apiResponse.ok) {
        throw new Error(`API returned status ${apiResponse.status}`);
      }

      const data = await apiResponse.json();
      const textResponse = data.choices?.[0]?.message?.content || "No response generated by AI.";

      setIsThinking(false);
      addMessage("assistant", textResponse);
    } catch (err: any) {
      console.error(err);
      setIsThinking(false);
      addMessage("assistant", `⚠️ Connection Error: Failed to contact local Llama 3.1 model. (${err.message})`);
    }
  };

  const parseMarkdownToComponents = (text: string) => {
    const lines = text.split("\n");
    const components: React.ReactNode[] = [];
    let currentBulletList: React.ReactNode[] = [];

    const flushBullets = (key: string) => {
      if (currentBulletList.length > 0) {
        components.push(
          <ul key={key} className="list-disc pl-5 space-y-1 my-2 text-zinc-300">
            {currentBulletList}
          </ul>
        );
        currentBulletList = [];
      }
    };

    const renderTextWithFormatting = (line: string) => {
      const parts = line.split(/(\*\*.*?\*\*)/g);
      return parts.map((part, index) => {
        if (part.startsWith("**") && part.endsWith("**")) {
          return <strong key={index} className="font-bold text-white">{part.slice(2, -2)}</strong>;
        }
        return <span key={index}>{part}</span>;
      });
    };

    lines.forEach((line, i) => {
      const trimmed = line.trim();
      
      if (trimmed.startsWith("* ") || trimmed.startsWith("- ")) {
        currentBulletList.push(
          <li key={`bullet-${i}`}>
            {renderTextWithFormatting(line.substring(2).trim())}
          </li>
        );
      } else {
        flushBullets(`bullets-${i}`);
        if (trimmed === "") {
           components.push(<div key={`br-${i}`} className="h-2" />);
        } else {
           components.push(
             <div key={`p-${i}`} className="my-1">
               {renderTextWithFormatting(line)}
             </div>
           );
        }
      }
    });

    flushBullets("bullets-end");
    return components.length > 0 ? components : text;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;
    addMessage("user", input);
    executeCommand(input);
    setInput("");
  };

  return (
    <div className="h-full flex flex-col bg-[#0B0B0D] text-white">
      {/* Header */}
      <div className="px-6 py-4 border-b border-[#22252C] flex items-center justify-between shrink-0 bg-[#0B0B0D]/80 backdrop-blur-md z-10">
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-[#FF6B35]/10 text-[#FF6B35] rounded-lg border border-[#FF6B35]/20">
            <BrainCircuit className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight text-white flex items-center space-x-2">
              <span>Warehouse Intelligence Copilot</span>
              <span className="px-1.5 py-0.5 rounded text-[8px] font-bold bg-[#FF6B35] text-black uppercase tracking-wider">
                Local AI
              </span>
            </h1>
            <p className="text-xs text-[#A1A1AA] flex items-center space-x-2 mt-0.5">
              <span className="w-1.5 h-1.5 rounded-full bg-[#22C55E] animate-pulse"></span>
              <span>Llama 3.1 Neural Engine • DB Linked</span>
            </p>
          </div>
        </div>
      </div>

      {/* Chat Area */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6 scrollbar-thin scrollbar-thumb-zinc-800">
        {messages.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center opacity-40">
            <Sparkles className="w-12 h-12 mb-4 text-[#A1A1AA]" />
            <p className="text-sm font-mono text-[#A1A1AA]">
              Awaiting query...
            </p>
          </div>
        ) : (
          messages.map((msg) => (
            <div
              key={msg.id}
              className={`flex ${msg.sender === "user" ? "justify-end" : "justify-start"}`}
            >
              <div
                className={`max-w-[75%] rounded-2xl p-4 flex flex-col space-y-2 ${
                  msg.sender === "user"
                    ? "bg-[#FF6B35] text-black rounded-tr-sm"
                    : "bg-[#171A20] border border-[#22252C] text-white rounded-tl-sm shadow-xl"
                }`}
              >
                <div className="flex items-center space-x-2 mb-1">
                  {msg.sender === "user" ? (
                    <User className="w-3.5 h-3.5" />
                  ) : (
                    <Terminal className="w-3.5 h-3.5 text-[#FF6B35]" />
                  )}
                  <span className="text-[10px] font-bold tracking-wider uppercase opacity-60">
                    {msg.sender === "user" ? "Operator" : "Copilot"} • {msg.timestamp}
                  </span>
                </div>
                <div className={`text-sm leading-relaxed whitespace-pre-wrap ${msg.sender === "user" ? "font-medium" : "font-mono"}`}>
                  {msg.sender === "assistant" ? parseMarkdownToComponents(msg.text) : msg.text}
                </div>
              </div>
            </div>
          ))
        )}

        {isThinking && (
          <div className="flex justify-start">
            <div className="max-w-[75%] rounded-2xl rounded-tl-sm p-4 bg-[#171A20] border border-[#22252C] shadow-xl">
              <div className="flex items-center space-x-2 text-[#A1A1AA]">
                <div className="flex space-x-1">
                  <div className="w-1.5 h-1.5 bg-[#FF6B35] rounded-full animate-bounce" style={{ animationDelay: "0ms" }}></div>
                  <div className="w-1.5 h-1.5 bg-[#FF6B35] rounded-full animate-bounce" style={{ animationDelay: "150ms" }}></div>
                  <div className="w-1.5 h-1.5 bg-[#FF6B35] rounded-full animate-bounce" style={{ animationDelay: "300ms" }}></div>
                </div>
                <span className="text-xs font-mono animate-pulse">Llama 3.1 is thinking...</span>
              </div>
            </div>
          </div>
        )}
        <div ref={chatEndRef} />
      </div>

      {/* Input Area */}
      <div className="p-4 bg-[#0B0B0D] border-t border-[#22252C]">
        <form onSubmit={handleSubmit} className="relative max-w-4xl mx-auto">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask about inventory, misplaced items, or operational status..."
            className="w-full bg-[#121317] text-white placeholder-zinc-500 rounded-xl pl-4 pr-12 py-3.5 outline-none border border-[#22252C] focus:border-[#FF6B35]/50 transition-all text-sm shadow-inner"
          />
          <button
            type="submit"
            disabled={!input.trim() || isThinking}
            className="absolute right-2 top-1/2 -translate-y-1/2 p-2 bg-[#FF6B35] hover:bg-[#ff7b4b] disabled:bg-zinc-800 disabled:text-zinc-600 text-black rounded-lg transition-all"
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
        <div className="text-center mt-2">
          <span className="text-[10px] text-zinc-600 uppercase tracking-widest font-mono">
            Powered by local LLama 3.1 • TanStack Query Context
          </span>
        </div>
      </div>
    </div>
  );
};
